default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: poke_wallet_development
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

test:
  <<: *default
  database: poke_wallet_test

production:
  <<: *default
  database: poke_wallet_production
  username: poke_wallet
  password: <%= ENV["POKE_WALLET_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>